# Use &filename to create a reference to an output. Inputs in later steps can
# use *filename to dereference the filename and create an explicit edge.
steps:
  - grompp:
      in:
        config:
          mdp:
            integrator: sd
            rvdw: 1.0
            rcoulomb: 1.0
            coulombtype: pme
            nsteps: 10000
            dt: 0.002
            tc-grps: system
            ref-t: 298
            tau-t: 2
            constraints: h-bonds
            nstxout: 100
            nstenergy: 100
            pcoupl: parrinello-rahman
            tau-p: 1
            ref-p: 1
            compressibility: 4.5e-5
            comm-mode: linear
            comm-grps: system
        output_tpr_path: '&prod.tpr'
        input_top_zip_path: '*genion.zip'  # Use the original topology file so
# we don't have to question whether the topology gets messed up after file format conversions.
# (In fact, it is not exactly identical!)
  - mdrun:
      in:
        output_crd_path: '&prod.gro'
        output_trr_path: '&prod.trr' # Explicitly specify for cwl_watcher
        output_edr_path: '&prod.edr'
        #config: '{use_gpu: True}'
  - cwl_watcher_analysis.yml:

wic:
  graphviz:
    label: Production
  steps:
    (1, grompp):
      wic:
        graphviz:
          label: 'Update\nTopology'
    (2, mdrun):
      wic:
        graphviz:
          label: 'Molecular\nDynamics'
    (3, cwl_watcher_analysis.yml):
      wic:
        backend: protein
        graphviz:
          label: 'Real-time\nAnalysis'
          style: invis # Make this node invisible
