name: Build And Run Test on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request: 
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  Build_and_Run_PyTest:
    name: Build and Run PyTest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: wic
        channels: conda-forge

    - name: Install System Dependencies from Conda
# The version of cwltool in apt (2.0.20200224214940) does not support CWL version 1.2
#      run: sudo apt install cwltool
# Use conda to install cwltool (version 3.1.20220224085855)
      working-directory: ${{github.workspace}}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        conda install cwltool
        ./conda_devtools.sh

    - name: Install System Graphviz (NOT python3-graphviz)
      run: sudo apt install graphviz

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install Python Dependencies from pip
      run: python -m pip install --upgrade graphviz
# NOTE: This 'graphviz' refers to the python bindings to the underlying
# system binary graphviz package (i.e. the `dot` executable) which we need to 
# install separately using either `conda install graphviz` or `sudo apt install graphviz`.
# This 'graphviz' is equivalent to `conda install python-graphviz` or
# `sudo apt install python3-graphiviz` ONLY.

    - name: Install Workflow Inference Compiler
      working-directory: ${{github.workspace}}
      run: python3 setup.py install

    - name: Run MyPy
      working-directory: ${{github.workspace}}
      # NOTE: Do not use `mypy .` because then mypy will check both src/ and build/ causing:
      # src/wic/__init__.py: error: Duplicate module named "wic" (also at "./build/lib/wic/__init__.py")
      run: mypy src/ tests/ *.py

    - name: Run PyLint
      working-directory: ${{github.workspace}}
      # NOTE: See fail-under threshold in .pylintrc
      run: pylint src/ tests/ *.py

    - name: Run PyTest
      working-directory: ${{github.workspace}}
      # NOTE: See fail_under threshold in .coveragerc
      run: pytest --cov --workers 4
